Test

diff --git a/.github/workflows/notify.yml b/.github/workflows/notify.yml
--- a/.github/workflows/notify.yml
+++ b/.github/workflows/notify.yml
@@ -14,121 +14,140 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Notify Allure Results to Telegram
-        uses: evgnick/allure-telegram@v1.0.0
+      - name: Find the latest CI run
+        uses: actions/github-script@v6
+        id: find_ci_run
         with:
+          script: |
+            const runs = await github.rest.actions.listWorkflowRunsForRepo({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              per_page: 50,
+            });
+            const ciRuns = runs.data.workflow_runs
+              .filter(run => run.name === "CI" && run.status === "completed" && (run.conclusion === "success" || run.conclusion === "failure"))
+              .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
+            const latestCiRun = ciRuns[0];
+            const runNumber = latestCiRun.run_number;
+            core.setOutput("run_number", runNumber);
+            core.setOutput("run_id", latestCiRun.id);
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+      - uses: actions/checkout@v4
+      - name: Run Allure Telegram Action
+        uses: your-username/allure-telegram-action@v1.0.0
+        with:
+          report_url: "https://redroverschool.github.io/JenkinsQA_2024_fall/${{ github.run_number }}/widgets/summary.json"
           telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
           chat_id: "-1002222760706"
-          ci_name: "CI"
 
-#      - name: Install dependencies
-#        run: pip install matplotlib
-#
-#      - name: Fetch test results from Allure report
-#        run: |
-#          REPORT_URL="https://evgnick.github.io/JenkinsQA_2024_fall2/${{ steps.find_ci_run.outputs.run_number }}/widgets/summary.json"
-#
-#          wget -q -O summary.json "$REPORT_URL" || { echo "Failed to download report"; exit 1; }
-#
-#          PASSED=$(jq '.statistic.passed' summary.json || echo "0")
-#          FAILED=$(jq '.statistic.failed' summary.json || echo "0")
-#          BROKEN=$(jq '.statistic.broken' summary.json || echo "0")
-#          SKIPPED=$(jq '.statistic.skipped' summary.json || echo "0")
-#          DURATION=$(jq '.time.duration' summary.json || echo "0")
-#          DURATION_FINAL=$(date -ud @$((DURATION / 1000)) +'%M:%S')
-#
-#          echo "PASSED=$PASSED" >> $GITHUB_ENV
-#          echo "FAILED=$FAILED" >> $GITHUB_ENV
-#          echo "BROKEN=$BROKEN" >> $GITHUB_ENV
-#          echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV
-#          echo "DURATION_FINAL=$DURATION_FINAL" >> $GITHUB_ENV
-#
-#      - name: Generate test results donut chart
-#        run: |
-#          python -c "
-#          import matplotlib.pyplot as plt
-#          import os
-#          from matplotlib import patches
-#
-#          passed = int(os.getenv('PASSED', 0))
-#          failed = int(os.getenv('FAILED', 0))
-#          broken = int(os.getenv('BROKEN', 0))
-#          skipped = int(os.getenv('SKIPPED', 0))
-#
-#          labels = ['Passed', 'Failed', 'Broken', 'Skipped']
-#          values = [passed, failed, broken, skipped]
-#          colors = ['#8BC34A', '#F44336', '#FF9800', '#2196F3']
-#
-#          fig, ax = plt.subplots(figsize=(3, 2))
-#          wedges, texts, autotexts = ax.pie(
-#              values, labels=None, autopct='%1.1f%%', colors=colors,
-#              startangle=90, wedgeprops={'edgecolor': 'white', 'linewidth': 2}, pctdistance=0.85,
-#          )
-#
-#          for autotext in autotexts:
-#              if float(autotext.get_text().replace('%', '')) == 0:
-#                  autotext.set_text('')
-#              autotext.set_fontsize(6)
-#
-#          centre_circle = plt.Circle((0, 0), 0.60, fc='white')
-#          fig.gca().add_artist(centre_circle)
-#
-#          ax.text(0, 0, str(sum(values)), ha='center', va='center', fontsize=16, fontweight='bold')
-#
-#          legend_x = 1.05
-#          legend_y = 0.6
-#          plt.gca().set_position([0, 0, 0.7, 1])
-#
-#          total = sum(values)
-#          percentages = [(value / total) * 100 if total > 0 else 0 for value in values]
-#
-#          for i, (label, color, value) in enumerate(zip(labels, colors, values)):
-#            rect = patches.Rectangle(
-#              (legend_x - 0.07, legend_y - i * 0.1 - 0.025),
-#              0.05, 0.05, color=color, transform=ax.transAxes, clip_on=False
-#            )
-#            plt.gcf().add_artist(rect)
-#
-#            plt.gcf().text(
-#              legend_x - 0.35,
-#              legend_y - i * 0.1,
-#              f'{value} - {label}',
-#              color='black', fontsize=8,
-#              bbox=dict(facecolor='white', edgecolor='white', boxstyle='square,pad=0.3'),
-#              ha='left', va='center'
-#            )
-#
-#          plt.savefig('chart.png', dpi=300, bbox_inches='tight', pad_inches=0.05)
-#          "
-#
-#      - name: Send Telegram Notification
-#        run: |
-#          REPORT_LINK="https://evgnick.github.io/JenkinsQA_2024_fall2/${{ steps.find_ci_run.outputs.run_number }}/"
-#          CI_RUN_LINK="https://github.com/evgnick/JenkinsQA_2024_fall2/actions/runs/${{ steps.find_ci_run.outputs.run_id }}"
-#
-#          TIMESTAMP=$(date +"%Y.%m.%d %H:%M:%S")
-#
-#
-#          ESCAPED_REPORT_LINK=$(echo "$REPORT_LINK" | sed 's|:|\\:|g; s|/|\\/|g')
-#          ESCAPED_CI_RUN_LINK=$(echo "$CI_RUN_LINK" | sed 's|:|\\:|g; s|/|\\/|g')
-#          ESCAPED_TIMESTAMP=$(echo "$TIMESTAMP" | sed 's|-|\\-|g; s|\.|\\.|g')
-#
-#          MESSAGE="📝 Report: [open](${ESCAPED_REPORT_LINK})
-#          📅 Data and time: ${ESCAPED_TIMESTAMP}
-#          ⏱️ Execution time: $DURATION_FINAL
-#          ⚙️ Build: ${{ steps.find_ci_run.outputs.run_number }}
-#          🔗 Run: [see](${ESCAPED_CI_RUN_LINK})"
-#
-#          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed -E 's/([\\`*_{}\[\]()#+\-!|<>])/\\\1/g')
-#
-#          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendPhoto" \
-#          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
-#          -F photo="@chart.png" \
-#          -F caption="$ESCAPED_MESSAGE" \
-#          -F parse_mode="MarkdownV2"
+      - name: Install dependencies
+        run: pip install matplotlib
+
+      - name: Fetch test results from Allure report
+        run: |
+          REPORT_URL="https://evgnick.github.io/JenkinsQA_2024_fall2/${{ steps.find_ci_run.outputs.run_number }}/widgets/summary.json"
+          
+          wget -q -O summary.json "$REPORT_URL" || { echo "Failed to download report"; exit 1; }
+          
+          PASSED=$(jq '.statistic.passed' summary.json || echo "0")
+          FAILED=$(jq '.statistic.failed' summary.json || echo "0")
+          BROKEN=$(jq '.statistic.broken' summary.json || echo "0")
+          SKIPPED=$(jq '.statistic.skipped' summary.json || echo "0")
+          DURATION=$(jq '.time.duration' summary.json || echo "0")
+          DURATION_FINAL=$(date -ud @$((DURATION / 1000)) +'%M:%S')
+          
+          echo "PASSED=$PASSED" >> $GITHUB_ENV
+          echo "FAILED=$FAILED" >> $GITHUB_ENV
+          echo "BROKEN=$BROKEN" >> $GITHUB_ENV
+          echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV
+          echo "DURATION_FINAL=$DURATION_FINAL" >> $GITHUB_ENV
+
+      - name: Generate test results donut chart
+        run: |
+          python -c "
+          import matplotlib.pyplot as plt
+          import os
+          from matplotlib import patches 
+          
+          passed = int(os.getenv('PASSED', 0))
+          failed = int(os.getenv('FAILED', 0))
+          broken = int(os.getenv('BROKEN', 0))
+          skipped = int(os.getenv('SKIPPED', 0))
+          
+          labels = ['Passed', 'Failed', 'Broken', 'Skipped']
+          values = [passed, failed, broken, skipped]
+          colors = ['#8BC34A', '#F44336', '#FF9800', '#2196F3']
+          
+          fig, ax = plt.subplots(figsize=(3, 2))
+          wedges, texts, autotexts = ax.pie(
+              values, labels=None, autopct='%1.1f%%', colors=colors,
+              startangle=90, wedgeprops={'edgecolor': 'white', 'linewidth': 2}, pctdistance=0.85,
+          )
+          
+          for autotext in autotexts:
+              if float(autotext.get_text().replace('%', '')) == 0:
+                  autotext.set_text('')
+              autotext.set_fontsize(6)
+          
+          centre_circle = plt.Circle((0, 0), 0.60, fc='white')
+          fig.gca().add_artist(centre_circle)
+          
+          ax.text(0, 0, str(sum(values)), ha='center', va='center', fontsize=16, fontweight='bold')
+          
+          legend_x = 1.05
+          legend_y = 0.6
+          plt.gca().set_position([0, 0, 0.7, 1])
+          
+          total = sum(values)
+          percentages = [(value / total) * 100 if total > 0 else 0 for value in values]
+          
+          for i, (label, color, value) in enumerate(zip(labels, colors, values)):
+            rect = patches.Rectangle(
+              (legend_x - 0.07, legend_y - i * 0.1 - 0.025),
+              0.05, 0.05, color=color, transform=ax.transAxes, clip_on=False
+            )
+            plt.gcf().add_artist(rect)
+          
+            plt.gcf().text(
+              legend_x - 0.35,
+              legend_y - i * 0.1,
+              f'{value} - {label}',
+              color='black', fontsize=8,
+              bbox=dict(facecolor='white', edgecolor='white', boxstyle='square,pad=0.3'),
+              ha='left', va='center'
+            )
+          
+          plt.savefig('chart.png', dpi=300, bbox_inches='tight', pad_inches=0.05)
+          "          
+
+      - name: Send Telegram Notification
+        run: |
+          REPORT_LINK="https://evgnick.github.io/JenkinsQA_2024_fall2/${{ steps.find_ci_run.outputs.run_number }}/"
+          CI_RUN_LINK="https://github.com/evgnick/JenkinsQA_2024_fall2/actions/runs/${{ steps.find_ci_run.outputs.run_id }}"
+
+          TIMESTAMP=$(date +"%Y.%m.%d %H:%M:%S")
+
+
+          ESCAPED_REPORT_LINK=$(echo "$REPORT_LINK" | sed 's|:|\\:|g; s|/|\\/|g')
+          ESCAPED_CI_RUN_LINK=$(echo "$CI_RUN_LINK" | sed 's|:|\\:|g; s|/|\\/|g')
+          ESCAPED_TIMESTAMP=$(echo "$TIMESTAMP" | sed 's|-|\\-|g; s|\.|\\.|g')
+
+          MESSAGE="📝 Report: [open](${ESCAPED_REPORT_LINK})
+          📅 Data and time: ${ESCAPED_TIMESTAMP}
+          ⏱️ Execution time: $DURATION_FINAL
+          ⚙️ Build: ${{ steps.find_ci_run.outputs.run_number }}
+          🔗 Run: [see](${ESCAPED_CI_RUN_LINK})"
+
+          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed -E 's/([\\`*_{}\[\]()#+\-!|<>])/\\\1/g')
+
+          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendPhoto" \
+          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
+          -F photo="@chart.png" \
+          -F caption="$ESCAPED_MESSAGE" \
+          -F parse_mode="MarkdownV2"
 
 #          ESCAPED_REPORT_LINK=$(echo "$REPORT_LINK" | sed 's|:|\\:|g; s|/|\\/|g')
 #          ESCAPED_CI_RUN_LINK=$(echo "$CI_RUN_LINK" | sed 's|:|\\:|g; s|/|\\/|g')
